theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  plausible: lilianaoust.fr
  breadcrumb:
    position: none
  summary:
    position: hero
  search:
    active: false
  blocks:
    gallery:
      splide:
        speed: 0
        arrows: true
        autoplay: false
        type: loop
        autoHeight: true
        breakpoints:
          '992':
            destroy: true
  image_sizes:
    design_system:
      lightbox:
        disabled: true